"""
import turtle
turtle.shape("turtle")
finn = turtle.clone()
finn.shape("square")
finn.penup()
finn.goto(50,0)
finn.pendown()
finn.goto(150,0)
finn.stamp()
finn.goto(150,100)
finn.stamp()
finn.goto(50,100)
finn.stamp()
finn.goto(50,0)
finn.stamp()
charlie = turtle.clone()
charlie.shape("triangle")
charlie.penup()
charlie.goto(200,0)
charlie.pendown()
charlie.goto(300,0)
charlie.goto(250,100)
charlie.goto(200,0)
finn.clearstamps()
turtle.mainloop()
"""
"""
import turtle
turtle.bgcolor("purple")
w = turtle.clone()
y = turtle.clone()
g = turtle.clone()
b = turtle.clone()
w.color("white")
y.color("yellow")
g.color("green")
b.color("blue")
w.shape("circle")
y.shape("blank")
g.shape("blank")
b.shape("arrow")
w.pensize(3)
y.pensize(3)
g.pensize(6)
b.pensize(6)
g.forward(75)
g.back(75)
g.left(90)
g.forward(150)
y.penup()
y.left(90)
y.forward(150)
y.pendown()
y.forward(150)
y.left(90)
y.forward(75)
w.penup()
w.left(90)
w.forward(300)
w.left(90)
w.forward(75)
w.pendown()
w.left(90)
w.forward(150)
b.penup()
b.forward(75)
b.pendown()
b.left(90)
b.forward(150)
"""
import turtle
turtle.pendown()
def up():
    turtle.left(90)
    turtle.forward(50)

turtle.onkeypress(up, "w")
def down():
    turtle.right(90)
    turtle.forward(50)
turtle.onkeypress(down, "s")
def left():
    turtle.left(180)
    turtle.forward(50)
turtle.onkeypress(left, "a")
def right():
    turtle.forward(50)
turtle.onkeypress(right, "d")
turtle.listen()
    


